# list
GET http://localhost:9129/list?app=app1&env=dev&ns=public

### update
POST http://localhost:9129/update?app=app1&env=dev&ns=public
Content-Type: application/json

{
  "mc.a": "dev300",
  "mc.c": "cc200",
  "mc.d": "dd200"
}
